apiVersion: apps/v1
kind: Deployment
metadata:
  name: all-content-app
  namespace: crawler-apps
spec:
  replicas: 3 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: all-content-app
  template:
    metadata:
      labels:
        app: all-content-app
    spec:
    containers:
    - name: all-content-app
      image: mglue/all-content-app:1.1
      ports:
      - containerPort: 8080
