[![Build and Deploy]  (https://github.com/ThantZawLyn/All-Content-SocialMedia/actions/workflows/main.yml/badge.svg?branch=main)](https://github.com/ThantZawLyn/All-Content-SocialMedia/actions/workflows/main.yml)

name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu:22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          mglue/all-content-app:1.3
          mglue/all-content-app:1.3:${{ github.sha }}
      env:
        DOCKER_USERNAME: ${{ secrets.mglue }}
        DOCKER_PASSWORD: ${{ secrets.dckr_pat_QCeZIueOToMGOIGe5s6t26Uh2Pg }}

    - name: Deploy to Kubernetes
      run: kubectl apply -f deployment.yaml
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}